services:
  stats-db:
    image: postgres:15
    container_name: stats-db
    environment:
      POSTGRES_DB: ewm_stats
      POSTGRES_USER: stats
      POSTGRES_PASSWORD: stats
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stats"]
      interval: 5s
      retries: 5
    volumes:
      - stats-db:/var/lib/postgresql/data  # Сохранение данных

  stats-server:
    build: ewm-stats/server/  # <-- Добавь build из Dockerfile (скопирует JAR)
    container_name: stats-server
    depends_on:
      stats-db:
        condition: service_healthy
    ports:
      - "9090:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/ewm_stats
      SPRING_DATASOURCE_USERNAME: stats
      SPRING_DATASOURCE_PASSWORD: stats
      SPRING_JPA_HIBERNATE_DDL_AUTO: create  # <-- Переопределит yml (создаст таблицу)
    # volumes:
    #   - stats-server:/app  # Опционально, для dev

volumes:
  stats-db:
    driver: local